language: php
php:
- 7.3
before_script:
- travis_retry composer self-update
- travis_retry composer install --prefer-source --no-interaction
cache:
  directories:
  - "$HOME/.composer/cache"
script:
- "./vendor/bin/phing"
deploy:
  provider: heroku
  app: discoverist
  api_key:
    secure: jFf3zipocc4Qeb292xMvGlC7T5SHOg+oGqSRwudMdAiJEMqEEk3dpOb2MZ4L2BgYaDfzZK1QpvRETo6z1FRJ7BBYVxgURtLu2TysVnxA1PzawsjctAfbPFLlRxVjSpMHUE4y3mIkOppaYYdnGyOO+SaLhznnvXaNoLTllItMh13tyjMz7pUa6+AH7N2zJnwX1o/3d9ydif+7EcnVFKAMt7+bm0//R8Y4WmLMCjSC1/lisB+5qgatN7UL5/dZKBiZdIheDxlegYMqaU9H+r59jBgqYSAcsUhrzeA6pMMne2lLqYZi66pOEJS6S20bbNOVyMZwzJSQyE71CNy/E/RyKQlbkINbV30csiqWBxwfrasg0VPYN2quRFMJ/39nPw5kK+ebgwve2WkCS1DlSRU/gst1Ye1ghOrhQI33/NvOP2q6ZuCB0EHliNQSYlM4PfHo9KSWDx1SORFNos2z/8KDHJoQXXK6ZTWXmmxZRM9QvhSwQd8u8rJaHXUJBy5OZ1SLj6R2NZoK59PYZCtFtyEIOD8erBhnbBc0/YCYtlLYdB9ozfbNxeOVC5hgkSMd5bDjr2E2hGRpOrBdQ2zz/FCQ5zzOzzMU3eNYFfaE9Vw/9qbFzb1u5EeNOXcmFrv+OssfFvecM4gjf7sf8TgrudNXzRaxQwIQs7LgU8uTcB+OURw=
  run: composer publish:assets
